export const OPPORTUNITY_SEED = [
  {
    sourcePlatform: 'Outlier',
    sourceUrl: 'https://outlier.ai/',
    title: 'AI Response Evaluation',
    summary:
      'Review model responses for accuracy, instruction-following, and quality. Outlier publishes contributor programs for people who can evaluate AI output carefully.',
    category: 'Evaluation',
    skills: ['evaluation', 'writing', 'reasoning'],
    experienceRequirement: 'No prior AI-training experience required for many projects.',
    location: 'Remote',
    remoteStatus: 'remote',
    beginnerFriendly: true,
    eligibility: 'Typically open to eligible U.S. participants. Confirm current requirements on Outlier.',
  },
  {
    sourcePlatform: 'Outlier',
    sourceUrl: 'https://outlier.ai/',
    title: 'Domain Expert Contributor',
    summary:
      'Apply professional knowledge—finance, science, law, or another field—to help train models that need real-world expertise.',
    category: 'Research',
    skills: ['research', 'domain expertise', 'evaluation'],
    experienceRequirement: 'Professional domain experience is useful; AI background is not required.',
    location: 'Remote',
    remoteStatus: 'remote',
    beginnerFriendly: true,
    eligibility: 'Confirm eligibility on Outlier. Many projects prefer U.S.-based contributors.',
  },
  {
    sourcePlatform: 'DataAnnotation',
    sourceUrl: 'https://www.dataannotation.tech/',
    title: 'Writing and Rating Projects',
    summary:
      'DataAnnotation lists remote AI training and data work that often involves writing, comparing answers, and following detailed instructions.',
    category: 'Writing',
    skills: ['writing', 'editing', 'evaluation'],
    experienceRequirement: 'Strong writing and attention to detail. No coding required for many projects.',
    location: 'Remote',
    remoteStatus: 'remote',
    beginnerFriendly: true,
    eligibility: 'Confirm current location and account requirements on DataAnnotation.',
  },
  {
    sourcePlatform: 'DataAnnotation',
    sourceUrl: 'https://www.dataannotation.tech/',
    title: 'Coding Evaluation Projects',
    summary:
      'If you already write code, DataAnnotation periodically offers projects that evaluate or improve model-generated software.',
    category: 'Coding',
    skills: ['software', 'coding', 'evaluation'],
    experienceRequirement: 'Software experience is typically expected for coding tracks.',
    location: 'Remote',
    remoteStatus: 'remote',
    beginnerFriendly: false,
    eligibility: 'Confirm current requirements on DataAnnotation.',
  },
  {
    sourcePlatform: 'Handshake',
    sourceUrl: 'https://joinhandshake.com/ai/',
    title: 'Handshake AI Expert Work',
    summary:
      'Handshake AI connects people with expert-level AI training work. Review current openings and eligibility on Handshake.',
    category: 'Evaluation',
    skills: ['evaluation', 'research', 'communication'],
    experienceRequirement: 'Professional or academic expertise is often more important than prior AI-training work.',
    location: 'Remote',
    remoteStatus: 'remote',
    beginnerFriendly: true,
    eligibility: 'Typically oriented toward eligible U.S. participants. Verify on Handshake.',
  },
  {
    sourcePlatform: 'Handshake',
    sourceUrl: 'https://joinhandshake.com/ai/',
    title: 'Finance Domain AI Training',
    summary:
      'Finance and markets knowledge can be useful on expert AI programs. Check Handshake AI for current domain-specific work.',
    category: 'Finance',
    skills: ['finance', 'research', 'evaluation'],
    experienceRequirement: 'Finance or adjacent professional experience is useful.',
    location: 'Remote',
    remoteStatus: 'remote',
    beginnerFriendly: false,
    eligibility: 'Confirm eligibility on Handshake.',
  },
  {
    sourcePlatform: 'Snorkel',
    sourceUrl: 'https://snorkel.ai',
    title: 'Expert Data Collaboration',
    summary:
      'Snorkel works with experts to build and improve training data. Review current expert or contributor opportunities on Snorkel.',
    category: 'Research',
    skills: ['research', 'data', 'evaluation'],
    experienceRequirement: 'Domain expertise is typically more important than AI-training tenure.',
    location: 'Remote',
    remoteStatus: 'remote',
    beginnerFriendly: true,
    eligibility: 'Confirm current programs and eligibility on Snorkel.',
  },
  {
    sourcePlatform: 'micro1',
    sourceUrl: 'https://www.micro1.ai/experts',
    title: 'AI Expert Network',
    summary:
      'micro1 recruits experts to help train and evaluate AI systems. Browse current expert tracks on their site.',
    category: 'Evaluation',
    skills: ['evaluation', 'communication', 'domain expertise'],
    experienceRequirement: 'Professional expertise in a field is the usual starting point.',
    location: 'Remote',
    remoteStatus: 'remote',
    beginnerFriendly: true,
    eligibility: 'Confirm location and qualification requirements on micro1.',
  },
  {
    sourcePlatform: 'micro1',
    sourceUrl: 'https://www.micro1.ai/experts',
    title: 'Science and Technical Review',
    summary:
      'Scientific and technical backgrounds are often useful for expert AI evaluation. Check micro1 for current science-related tracks.',
    category: 'Science',
    skills: ['science', 'research', 'evaluation'],
    experienceRequirement: 'Science, engineering, or technical professional experience is useful.',
    location: 'Remote',
    remoteStatus: 'remote',
    beginnerFriendly: false,
    eligibility: 'Confirm requirements on micro1.',
  },
  {
    sourcePlatform: 'Outlier',
    sourceUrl: 'https://outlier.ai/',
    title: 'Creative and Writing Tasks',
    summary:
      'Some Outlier projects emphasize writing quality, comparison, and following editorial-style instructions.',
    category: 'Writing',
    skills: ['writing', 'editing', 'evaluation'],
    experienceRequirement: 'Comfortable written English. Prior AI-training work is not always required.',
    location: 'Remote',
    remoteStatus: 'remote',
    beginnerFriendly: true,
    eligibility: 'Typically requires eligible U.S. participants. Confirm on Outlier.',
  },
] as const;
